Update headers
parameter1/ac-business-media-newsletters pull request #12
Opened 2021-07-06 20:29 UTC by jwade1327

Still need to modify headers for Fleet Maintenance Report and Resource Center

2021-07-07 15:23 UTC, jwade1327 commented
-updated fleet maintenance report header
-currently ignoring resource center newsletter since it hasn't been deployed in 2 years

2021-07-09 14:44 UTC, brandonbk requested changes

2021-07-09 14:44 UTC, brandonbk commented on packages/common/components/blocks/header/psc-image.marko
> +          <img border="0" src=input.imageSrcRight align="left" height="100" width="310" alt=input.name/>
@jwade1327 - `<img>` tags should be replaced with `<marko-newsletter-imgix>` components.  See https://github.com/parameter1/pmmi-media-group-newsletters/blob/2a278ce6931dae61a66cf87ccb2943fc2ed796fa/packages/common/components/blocks/standard/header.marko#L67 for an example.

2021-07-09 14:44 UTC, brandonbk commented on packages/common/components/blocks/header/image.marko
>                <img border="0" src=input.imageSrc align="left" style="display:block" alt=input.name />
Use `<marko-newsletter-imgix>` instead of `<img>`

2021-07-30 19:31 UTC, brandonbk approved these changes

2021-07-30 19:31 UTC, merged