Create IronPros newsletter/layout
parameter1/ac-business-media-newsletters pull request #130
Opened 2022-10-13 19:09 UTC by jwade1327

![screencapture-localhost-21094-templates-breaking-ground-ironpros-2022-10-13-14_03_16](https://user-images.githubusercontent.com/64623209/195687661-2fdfb9ab-be2e-4755-a254-32c33049b732.png)

2022-10-13 19:12 UTC, jwade1327 commented
@B77Mills This is the best/furthest I can get.... 
**Drawing Attention to these areas**
-Top border of the 600x100 ad when I run through Email on Acid it shifts and becomes longer
-Can't get the overlay on the primary image to expand full length of image
-Footer image (not sure how else I can use it/get it to show as a background image)

2022-10-13 19:14 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [New Template for FCP](https://trello.com/c/NjGL9gLg/292-new-template-for-fcp)

2022-10-13 20:03 UTC, B77Mills commented on packages/common/components/blocks/content/ironpros-featured.marko
> +  $ const imgOptions = {
@jwade1327 

If they want the mark to span full with try updating the image options to the following
```
$ const imgOptions = {
    mark: `https://${newsletter.site.imageHost}/files/base/acbm/fcp/image/static/eqw_feature_overlay_2260.png`,
    markalign: 'bottom',
    markpad: '0',
    markscale: '100',
  };
  ```

2022-10-13 20:06 UTC, jwade1327 commented on packages/common/components/blocks/content/ironpros-featured.marko
> +  $ const imgOptions = {
@B77Mills That fixed it! Thanks!

2022-10-13 20:07 UTC, B77Mills requested changes

2022-10-13 20:07 UTC, B77Mills commented on packages/common/components/blocks/content/ironpros-sponsored-secondary.marko
> +                  <common-table-spacer-element height=25 />
@jwade1327 not sure about the spacing at the bottom here, but it looks like this and line 144 would get you a 60px spacer, but that might be intentional.

2022-10-13 20:07 UTC, B77Mills commented on packages/common/components/blocks/content/ironpros-workwear.marko
> +              <common-table-spacer-element height=35 />
@jwade1327 same spacing concern here with line 197

2022-10-13 20:11 UTC, jwade1327 commented on packages/common/components/blocks/content/ironpros-workwear.marko
> +              <common-table-spacer-element height=35 />
@B77Mills Yes it is intentional because the inner vs. outer background.
<img width="819" alt="Screen Shot 2022-10-13 at 3 10 16 PM" src="https://user-images.githubusercontent.com/64623209/195699613-6017e342-5ef7-4915-aea9-2a8b9d526f27.png">

2022-10-14 16:21 UTC, B77Mills approved these changes

2022-10-14 16:24 UTC, merged