New template adjustments
parameter1/ac-business-media-newsletters pull request #160
Opened 2023-06-16 17:37 UTC by jwade1327

![screencapture-localhost-21094-templates-breaking-ground-ironpros-2023-06-16-12_35_25](https://github.com/parameter1/ac-business-media-newsletters/assets/64623209/272921f2-c71a-412b-8865-f084d1313c78)
![screencapture-localhost-21094-templates-headline-news-ironpros-2023-06-16-12_35_04](https://github.com/parameter1/ac-business-media-newsletters/assets/64623209/75664283-c4f1-4364-8543-d8c53dd81dbd)
![screencapture-localhost-21095-templates-global-supply-chain-insights-2023-06-16-12_31_47](https://github.com/parameter1/ac-business-media-newsletters/assets/64623209/f57d40fe-5a26-4de7-996c-d02b90acf7b3)

2023-06-16 17:38 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [eNL Updates](https://trello.com/c/lZrpWuvD/406-enl-updates)

2023-06-19 20:25 UTC, B77Mills commented on packages/common/components/blocks/content/simple-list-item.marko
> +                          <common-table-spacer-element height="5" />
@jwade1327  Per our convo, I think colspan="4" is needed here so it would make a `<tr><td colspan="4" height="5" ></td></tr>`  on the inclusion. If you could confirm or it might get crabby in email on acid. :(

2023-06-19 20:44 UTC, B77Mills requested changes

2023-06-19 20:44 UTC, B77Mills commented on packages/common/components/blocks/standard-header.marko
> +              <common-table-spacer-element height=15 />
@jwade1327 This also needs the attributes prop.

2023-06-19 20:44 UTC, B77Mills commented on packages/common/components/blocks/ironpros-header.marko
> +              <common-table-spacer-element height=15 />
@jwade1327 This also needs the attributes prop.

2023-06-20 16:26 UTC, B77Mills approved these changes

2023-06-20 16:27 UTC, merged