Create static version of new standard footer
parameter1/ac-business-media-newsletters pull request #17
Opened 2021-08-09 14:25 UTC by jwade1327

2021-08-11 16:26 UTC, jwade1327 commented
<img width="1603" alt="Screen Shot 2021-08-11 at 11 25 43 AM" src="https://user-images.githubusercontent.com/64623209/129066832-df7dd49b-fe31-4886-841f-65262ae4511d.png">

2021-08-11 16:26 UTC, jwade1327 commented
@brandonbk screenshot added

2021-08-11 19:27 UTC, solocommand requested changes

2021-08-11 19:27 UTC, solocommand commented on packages/common/components/blocks/new-standard-footer.marko
> +              <td align="center" valign="middle"><img src="https://wfh0621.upupload.com/71644/rx1f7he0s271644/images/link.png" alt="link" width="35" height="34"></td>
These files should be moved to S3

2021-08-12 15:36 UTC, jwade1327 commented
These images are now added to S3 @solocommand

2021-08-12 16:16 UTC, solocommand commented
@jwade1327 looks good except the hostname! This should pull the image domain from the site (I'm sure we've done this on other static header images/etc elsewhere), resulting in `https://img.forconstructionpros.com/files/...` on FCP instead of `https://s3.amazonaws.com/media.base.parameter1.com/files/...`.

If you can't find an example let me know and I can hunt one down

2021-08-12 16:54 UTC, jwade1327 commented
@solocommand ok now I finally got it!

2021-08-16 13:12 UTC, brandonbk commented
@jwade1327 - this is fine for this first pass, since its intended to be static.  I was going to ask you to make the image host (img.sdcexec.com) dynamic or config-driven, so it wasn't forced to sdc's value, but that can come in a later pass when all of the social icons become config-driven.

2021-08-16 13:12 UTC, merged